export const MAX_DOCUMENT_CONTENT_LENGTH = 200_000;
export const MAX_CHUNK_CONTENT_LENGTH = 102_400;
export const MAX_CHUNK_COUNT = 200;
export const DOCUMENT_FILE_SIZE_LIMIT = 2 * 1024 * 1024;
export const DOCUMENT_FILE_COUNT_LIMIT = 10;
export const MARKDOWN_FILE_SIZE_LIMIT = DOCUMENT_FILE_SIZE_LIMIT;
